Layout/publication
kejjero/itmo pull request #3
Opened 2022-04-01 13:24 UTC by ViktorPekin

2022-04-02 19:40 UTC, hiksP commented on src/index.html
> +                <ul class="publications__container">
может здесь лучше подойдет название publications__list будет понятнее и не будет путаницы, а то практически два одинаковых названия

2022-04-02 19:40 UTC, hiksP commented on src/index.html
> +                        <div class="publication__container">
мб здесь подойдет тег article больше? не уверен)

2022-04-02 19:47 UTC, hiksP requested changes
https://prnt.sc/15LTJXUbh2gr
https://prnt.sc/xEDq51ZIbGQn
не хватает двух элементов на странице, стрелочек для пролистывания, и точек обозначающих где ты находишься, а так все впорядке грейт джоб

2022-04-03 07:01 UTC, ViktorPekin commented on src/index.html
> +                <ul class="publications__container">
Исправил

2022-04-03 07:04 UTC, ViktorPekin commented
> [https://prnt.sc/15LTJXUbh2gr ](https://prnt.sc/15LTJXUbh2gr) https://prnt.sc/xEDq51ZIbGQn не хватает двух элементов на странице, стрелочек для пролистывания, и точек попадания куда ты находишься, а так все в порядке грейт джоб

Я буду подключать https://swiperjs.com/ от туда берутся и кнопки и точки.

2022-04-03 07:04 UTC, ViktorPekin commented on src/index.html
> +                        <div class="publication__container">
Думаю это лучше чем div

2022-04-03 09:40 UTC, hiksP approved these changes

2022-04-03 09:41 UTC, merged